### ISSUE TITLE
Newer shockers can not be added via the ingame menu

### ISSUE THREAD

**Issue by Nirv-git** [Shock-Link/Integrations.TW#3]
When trying to add newly generated shockers via the TW integrations mod they fail to get added to the shockers list. No error message, or confirmation is shown in the menu and in the Melonloader console only the line `[ShockLink.Integrations.TW] PatchRegisterNewToken` prints. 

When putting in an invalid GUID it results in an error and if I remove and readd an older shocker it will add normally and show a confirmation message.

If you manually edit the `ChilloutVR\UserData\TotallyWholesome\TotallyWholesomeConfig.json` file and input the details of the new shocker it will show in game and work as expected. Just the 'Add Shocker' button is failing for some reason for these newer GUID's. 

Another user also noticed this issue, and reported it to me when I was helping them setup their Shocklink stuff. 

This was tested on 
TW 3.4.25 Release Build 
CVR 2023r172p2
MelonLoader v0.6.1 Open-Beta
WholesomeLoader v3.3.3
ShockLink.Integrations.TW v1.0.0 (This made me double check, but that is what the current release [version reports ](https://github.com/OpenShock/Integrations.TW/blob/585ad775e7b3773875a79e579f51758730a8a81a/TWShockLink/ShockLinkIntegrationTW.cs#L7)

**Comment by ddakebono** [comment]
Issue resolved with version 1.0.1.0, was due to some changes on the API side
